@startuml maquina_estados_furby

[*] --> HUEVO

state "HAMBRE + CANSADO" as HAMBRE_CANSADO
state "HAMBRE + SUCIO" as HAMBRE_SUCIO
state "HAMBRE + CANSADO + SUCIO" as HAMBRE_CANSADO_SUCIO
state CANSADO

HUEVO --> NORMAL : Nacer()

NORMAL --> HAMBRE : hambre <= 50%
NORMAL --> SUCIO : higiene <= 50%
NORMAL --> CANSADO : sueno <= 50%

CANSADO --> NORMAL : Despertar()
CANSADO --> HAMBRE_CANSADO : hambre <= 50%

HAMBRE --> NORMAL : Comer()
HAMBRE --> HAMBRE_CANSADO : sueno <= 50%
HAMBRE --> HAMBRE_SUCIO : higiene <= 50%

SUCIO --> NORMAL : Banar()
SUCIO --> HAMBRE_SUCIO : hambre <= 50%

HAMBRE_CANSADO --> CANSADO : Comer()
HAMBRE_CANSADO --> HAMBRE_SUCIO : higiene <= 50%
HAMBRE_CANSADO --> HAMBRE_CANSADO_SUCIO : higiene <= 50% y sueno <= 50%

HAMBRE_SUCIO --> SUCIO : Comer()
HAMBRE_SUCIO --> HAMBRE : Banar()

HAMBRE_CANSADO_SUCIO --> HAMBRE_CANSADO : Banar()
HAMBRE_CANSADO_SUCIO --> CANSADO : Comer()
HAMBRE_CANSADO_SUCIO --> HAMBRE : Despertar()

HAMBRE_CANSADO --> ENFERMO : salud <= 30%
HAMBRE_SUCIO --> ENFERMO : salud <= 30%
ENFERMO --> NORMAL : Curar()
ENFERMO --> MUERTO : salud <= 0%

MUERTO --> [*]

note right of MUERTO
  Estado final.
  Solo se sale con REVIVIR.
end note

@enduml